import Head from 'next/head'
import axios from 'axios'
import React, {useState ,useEffect} from "react";
import { useMutation, useQueryClient } from "react-query";
// import { useProducts } from "../hooks/api/useProduct";


export default function Home() {
  const [tableData, setTableData] = useState();
  // const checkData = res.data.rtnResult;

  const onPatchMutation = useMutation(
    () =>
      axios
        .patch(
          "http://172.17.72.128:8000/db2_sp",
          {
            p_language :"",
            p_plant: "P100",
            p_user: "user99",
            p_pgm: "sp_mobile_com_login",
            p_option: {
              input_user: "10051004",
              input_pass: "1234",
            },
          },
          { staleTime: 5000 }
        )
        .then((res) => console.log("요청 결과", res.data.rtnResult)),
    {
      onSuccess: () => queryClient.invalidateQueries(),
      onError: (error, variables, context) => {
        console.log(error);
      },
      
    }
    
  );
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='login'>
        <input type='text'/>
        <input type='password'/>
        <button onClick={() => onPatchMutation.mutate()}>패치</button>
        {/* <button onClick={data}>data</button> */}
      </div>
    </div>
  )
}
